// Copyright © 2026 Ivyware Pty Ltd, Khrustal & Mann
//              MELBOURNE, VICTORIA, AUSTRALIA, 3000
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.
//
//  PrintPHP - a Msgcore store as PHP class declarations.
//
//      P2PmsgMgr oMgr ( L"person.p2p" );
//      PrintPHP  oPHP;
//      oMgr >> oPHP;
//      oPHP.Save ( L"Person.php", false );
//
//  The output is PHP SOURCE - a class per structural node, each with a typed
//  property per field - and not a var_export dump. That is the difference that
//  decides everything below: source has to declare before it uses, property
//  initialisers have to be constant expressions, and identifiers have to be
//  identifiers, none of which a data dump has to care about.
//
//      <?php
//      //  Generated by MsgcoreUtils PrintPHP from Msgcore store 'Person'
//
//      class Person_Address
//      {
//          /** @var string  wstr16  (Msgcore 'Street') */
//          public $Street = "Smith St";
//      }
//
//      class Person
//      {
//          /** @var string  wstr16  (Msgcore 'Surname') */
//          public $Surname = "Mann";
//          /** @var int  int32  (Msgcore 'Age') */
//          public $Age = 42;
//          /** @var string[]  (Msgcore list 'Tags') */
//          public $Tags = array("staff", "melbourne");
//          /** @var Person_Address */
//          public $Address;
//
//          public function __construct ( )
//          {
//              $this->Address = new Person_Address();
//          }
//      }
//
//  THE MAPPING
//       : DESCENDANTS MAKE A CLASS. A node with descendants becomes a class
//         declaration, one property per descendant, and the parent holds it in
//         a property assigned by __construct. Everything else - the node's own
//         value, its attributes, and the elements of a list or vector -
//         follows the same shape PrintJson uses, expressed as PHP scalars and
//         arrays. One sentence covers the whole dialect, and it has to: a
//         second rule for lists-that-also-have-attributes would be a rule
//         nobody reading the output could infer from the output.
//       : The three synthetic properties are $_value (the node's own data),
//         $_items (the elements of a list or vector) and $_attributes (the
//         attribute set as an associative array). They appear only when the
//         node has that part.
//       : Nested arrays use the same sentinel keys as the JSON dialect -
//         '.value', '.items' and an @ prefix for attributes - which cannot
//         collide with an item name because P3Pmsg_IsValidItemname rejects
//         both delimiters. See PrintJson.h.
//
//  WHY CHILD CLASSES ARE DECLARED BEFORE THEIR PARENT: PHP hoists an
//  unconditional class declaration, so the order is not strictly required -
//  but a generated file is also read, diffed and pasted into a larger file
//  where hoisting no longer applies, and declare-before-use costs nothing.
//
//  WHY OBJECTS ARE ASSIGNED IN __construct AND NOT INITIALISED IN PLACE: a PHP
//  property initialiser must be a constant expression. Arrays, strings and
//  numbers are; `new` is not, in any PHP version this output targets. That is
//  also why a BLOB is emitted as its base64 STRING and not as a
//  base64_decode() call - a function call in an initialiser is a parse error,
//  so the decode belongs to the consumer.
//
//  IDENTIFIERS ARE SANITISED, NOT ASSUMED. A Msgcore item name may contain
//  spaces, hyphens and anything else P3Pmsg_IsValidItemname does not forbid -
//  none of which is a PHP identifier. Every name is reduced to [A-Za-z0-9_],
//  prefixed if it would start with a digit, and de-duplicated within its scope
//  with a numeric suffix. THE ORIGINAL NAME IS NOT LOST: it is carried in the
//  docblock above the property, which is the only place it can be recovered
//  from once the identifier has been folded.
//
//  STRINGS ARE DOUBLE-QUOTED with backslash, quote, dollar and every control
//  character escaped, the last as a full two-digit \xNN. Two digits and not
//  one because PHP takes UP TO two after \x, so a single-digit escape followed
//  by a hex character would swallow it and produce a different string.
//
#pragma once

#include <vector>                       // ahead of the Msgcore headers - see MsgPrint.h

#include "MsgPrint.h"

class MsgcoreUtils_EXT PrintPHP : public MsgPrint
{
    // Constructors and destructor
    public:
        PrintPHP ( ) noexcept;

        //  Seeds the renderer with a DOCUMENT, exactly as SetText does, so a
        //  parse needs no second statement:
        //
        //      PrintPHP oPHP ( strGeneratedSource );
        //      oMgr << oPHP;
        //
        //  TEXT, NOT A FILENAME, and explicit for that reason. Load() takes the
        //  filename, and both take an LPCTSTR, so an implicit conversion here
        //  would silently accept a path where a document belongs and parse the
        //  path as PHP source.
        //
        //  It carries the same indent default the default constructor sets, and
        //  has to: the base initialiser is 2 and PHP is written at 4, so a
        //  renderer built from a document and then RENDERED would otherwise
        //  emit at a width no other PrintPHP produces.
        //
        //  Not noexcept, unlike the default constructor: holding the text is an
        //  allocation.
      explicit
        PrintPHP ( LPCTSTR lpszText );

        PrintPHP ( const PrintPHP& rhs );

      virtual
       ~PrintPHP ( );

    // Operators
    public:
      PrintPHP&
        operator = ( const PrintPHP& rhs );

    // Rendering
    public:
      virtual MsgPrint&
        Render ( P3PmsgItem& oItem );

    // Parsing
    //  NOTES: Reads the PHP this renderer HOLDS into oItem, replacing what
    //         oItem held. WHAT IT READS IS THIS RENDERER'S OWN OUTPUT - see the
    //         definition. It is not a PHP parser and does not claim to be one:
    //         JSON has a grammar anything can write, PHP source does not, so
    //         the honest scope of this direction is the round trip.
    //       : It depends on the DOCBLOCKS. The property identifiers are folded
    //         by Sanitise on the way out, so the item's real name and its
    //         Msgcore type survive only in the comment above it - which is what
    //         lets this dialect restore the exact type byte where JSON can only
    //         infer a width, and what makes a stripped file unreadable.
    public:
      virtual MsgPrint&
        Parse ( P3PmsgItem& oItem );

    // Properties
    public:
      //  The name of the root class, and the prefix every nested class name is
      //  built from. Empty (the default) takes it from the rendered item name,
      //  which for a manager is the store root name. Set it when the root name
      //  is not one you want in your source - it is sanitised either way.
      LPCTSTR
        SetClassName ( LPCTSTR lpszClassName );
      LPCTSTR
        GetClassName ( ) const noexcept;
      //  Whether the opening <?php tag and the generated-by banner are emitted.
      //  Off when the output is being spliced into a file that already has one.
      bool
        SetPreamble ( bool bPreamble ) noexcept;
      bool
        GetPreamble ( ) const noexcept;

    // Implementation
    private:
      //  Appends the class declarations for oItem - its descendants first, then
      //  itself. strClass is already sanitised and already unique.
      void
        RenderClass ( P3PmsgItem& oItem, const CString& strClass, int nDepth );

      //  A node rendered as a PHP VALUE expression: scalar, array, or the
      //  associative array form when it carries attributes as well.
      CString
        NodeValue ( P3PmsgItem& oItem, int nDepth ) const;
      CString
        ScalarValue ( P3PmsgData& oData ) const;
      CString
        ListValue ( P3PmsgList& oList, int nDepth ) const;
      CString
        VectValue ( P3PmsgVect& oVect, int nDepth ) const;
      CString
        AttrValue ( P3PmsgAttr& oAttr, int nDepth ) const;

      //  Layout. The indent is the WIDTH of a level; unlike the JSON dialect,
      //  0 does not collapse the file onto one line - it only removes the
      //  padding - because a // comment needs a line to end. It does collapse
      //  an ARRAY LITERAL, which has no comments in it.
      CString
        Pad ( int nDepth ) const;
      //  The separator in front of an array entry, which is where the comma
      //  lives: nothing before the first, a comma before the rest, and a break
      //  plus padding when the indent asks for one. Clears bFirst.
      CString
        Pad ( int nDepth, bool& bFirst ) const;

      //  Identifier hygiene. Unique() appends the smallest numeric suffix that
      //  makes strName absent from oTaken, and records it there.
      static CString
        Sanitise ( LPCTSTR lpszName, LPCTSTR lpszFallback );
      static CString
        Unique ( const CString& strName, std::vector<CString>& oTaken );
      static CString
        Escape ( LPCTSTR lpszText );

    // Attributes
    private:
      CString  m_strClassName;
      bool     m_bPreamble{true};
      //  Every class name emitted by the render in progress, so a second node
      //  that sanitises to a name already taken gets a suffix rather than
      //  silently redeclaring the first. Cleared at the start of each Render.
      std::vector<CString> m_oClassNames;

    // Reading
    private:
      //  Where one class declaration is in the held text. Filled by
      //  ReadClasses at the start of a parse and indexed by the constructor
      //  resolution, which names a class the reader has already walked past.
      struct PHPClass
      {
        CString strName;
        int     nBody{0};              // First character after the '{'
        int     nEnd{0};               // The matching '}'
      };
      std::vector<PHPClass> m_oClasses;

      bool
        ReadClasses ( );
      bool
        ReadClass ( size_t nClass, MsgValue& oValue, int nDepth );
      bool
        ReadCtor ( int& nPos, int nEnd
                 , std::vector<CString>& oProp, std::vector<CString>& oClass );
      bool
        ReadExpr ( MsgValue& oValue, int& nPos, int nDepth );
      bool
        ReadArrayExpr ( MsgValue& oValue, int& nPos, int nDepth );
      bool
        ReadPHPString ( CString& strOut, int& nPos );
      bool
        ReadIdent ( CString& strOut, int& nPos ) const;
      bool
        ReadWord ( LPCTSTR lpszWord, int& nPos ) const;
      void
        SkipTrivia ( int& nPos ) const;
      void
        SkipTriviaDoc ( int& nPos, CString& strDoc ) const;
      void
        SkipString ( int& nPos ) const;
      int
        FindClass ( LPCTSTR lpszName ) const;

      //  The two things only a docblock still knows.
      static bool
        DocName ( const CString& strDoc, CString& strName );
      static CString
        DocType ( const CString& strDoc );
};

///////////////////////////////////////////////////////////////////////
//  Rendering operator
//  NOTES: On P3PmsgItem for the same reason PrintJson's is - P2PmsgMgr derives
//         from it, so one declaration serves the whole object model.
MsgcoreUtils_EXT PrintPHP&
operator >> ( P3PmsgItem& oItem, PrintPHP& oPHP );

//  NOTES: The reversed spelling of the same render, as PrintJson has - and it
//         REPLACES too, so a second << does not add a second set of class
//         declarations to the first.
MsgcoreUtils_EXT PrintPHP&
operator << ( PrintPHP& oPHP, P3PmsgItem& oItem );

///////////////////////////////////////////////////////////////////////
//  Parsing operators
//  NOTES: The same pair as PrintJson's, and the arrow points the same way -
//         at the thing being written:
//
//             oMgr >> oPHP;   oPHP << oMgr;    render - store into text
//             oMgr << oPHP;   oPHP >> oMgr;    parse  - text into store
//
//       : All four return the renderer, whichever side it is written on, so
//         the outcome is reachable from the expression - and a parse has to be
//         asked: (oMgr << oPHP).GetError().
MsgcoreUtils_EXT PrintPHP&
operator << ( P3PmsgItem& oItem, PrintPHP& oPHP );

MsgcoreUtils_EXT PrintPHP&
operator >> ( PrintPHP& oPHP, P3PmsgItem& oItem );
